#!/usr/bin/env bash
# A bash script that displays the subdomain information

subdom_info () {

	my_subdoms=("www" "lb-01" "web-01" "web-02")
	if [ -z "$2" ]; then
		for i in "${my_subdoms[@]}"; do
			dig "$i.$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{split($0, SUBDOMAIN, "."); print "The subdomain " SUBDOMAIN[1] " is a " $4 " record and points to " $5}'
		done
	else
		dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{split($0, SUBDOMAIN, "."); print "The subdomain " SUBDOMAIN[1] " is a " $4 " record and points to " $5}'
	fi
}
subdom_info "$1" "$2"
